// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.35;

import {CfdEnginePlanTypes} from "@plether/perps/CfdEnginePlanTypes.sol";
import {CfdTypes} from "@plether/perps/CfdTypes.sol";

/// @title Canonical delayed-order types (V3 intent / V4 receipts)
/// @notice Versioned request, policy, assessment, and receipt tuples. The library name is retained for source continuity.
/// @custom:security-contact contact@plether.com
library OrderV2Types {

    enum CloseMode {
        Standard,
        CallerPaidFullExit
    }
    enum ReservationDiscrepancy {
        None,
        MissingOrSettled,
        Identity,
        Amount,
        LedgerInvariant
    }

    struct CloseEconomics {
        uint256 postFreeSettlementUsdc;
        uint256 safeMarginReleaseUsdc;
        uint256 actionChargeFromReleasedMarginUsdc;
        uint256 netReleasedMarginUsdc;
        uint256 priceLossUsdc;
        uint256 pricePnlClaimConsumedUsdc;
        uint256 pricePnlPledgeConsumedUsdc;
        uint256 priceLossWrittenOffUsdc;
        uint256 actionChargeWithheldUsdc;
        uint256 actionChargeWaivedUsdc;
    }

    struct BountyAccounting {
        uint256 bountyEntitlementUsdc;
        uint256 bountyPaidUsdc;
        uint256 bountyRefundedUsdc;
        uint256 bountyRetainedUsdc;
        uint256 bountyForfeitedUsdc;
        ReservationDiscrepancy discrepancy;
    }

    /// @notice Prefix reserved for client ids generated by immutable protocol components.
    /// @dev The remaining 192 bits retain a truncated tagged digest. Public bounded orders must not use this prefix.
    bytes8 internal constant PROTOCOL_CLIENT_ORDER_ID_PREFIX = 0x504c455448455221;

    /// @notice Lifecycle state stored by the immutable order book.
    enum LifecycleStatus {
        None,
        Pending,
        Executed,
        Failed
    }

    /// @notice Result of resolving a client-supplied id in an account namespace.
    enum ClientIntentResolution {
        Unused,
        ExactReplay,
        Conflict
    }

    /// @notice Execution regime selected from authoritative protocol state.
    enum ExecutionMode {
        None,
        Live,
        Fad,
        Frozen
    }

    /// @notice Source of the price reported in a terminal receipt.
    enum PriceSource {
        None,
        OracleExecution,
        CachedMark,
        Liquidation
    }

    /// @notice Final disposition of the order's reserved keeper bounty.
    enum BountyDisposition {
        None,
        Paid,
        Forfeited,
        RefundedToAccount,
        /// @notice The bounty remains reserved for a fresh attempt of the same latched position protection.
        RetainedForProtectionRetry
    }

    /// @notice Canonical reason for a terminal order transition.
    enum TerminalReason {
        None,
        Executed,
        Expired,
        Slippage,
        ConfigMismatch,
        ExecutionModeDisallowed,
        RiskOff,
        PlannerRejected,
        ConstraintViolation,
        AccountLiquidated,
        TerminalPositionChanged,
        ExpiredReservationMismatch
    }

    /// @notice Financial constraint tested by the policy evaluator.
    /// @dev Ordering is canonical and is also the required evaluation order.
    enum ConstraintKind {
        None,
        ExecutionBounty,
        ExecutionNotional,
        GrossAccountDebit,
        ActionCharge,
        ExplicitFees,
        PostPositionSize,
        PostSettlementBalance,
        PostPositionEquity,
        PostLeverage
    }

    /// @notice Why an execution call left the current order pending.
    enum PendingReason {
        None,
        CloseOnly,
        SameBlock,
        MevBoundary,
        HistoricalPriceUnavailable,
        InsufficientGas,
        MarkPriceOutOfOrder,
        EngineFailure,
        ReceiptFailure,
        CleanupLimit
    }

    /// @notice Mandatory financial authority supplied with every V2 order.
    /// @dev Maximum values are inclusive and zero is a real zero allowance. Minimum values are inclusive.
    ///      `maxGrossAccountDebitUsdc` covers settlement debit, trader-claim consumption, and the reserved bounty;
    ///      `minPostSettlementBalanceUsdc` refers to total internal settlement custody, including locked value.
    struct ExecutionBounds {
        uint64 validUntil;
        uint8 allowedExecutionModes;
        bytes32 expectedConfigHash;
        uint256 maxExecutionBountyUsdc;
        uint256 maxExecutionNotionalUsdc;
        uint256 maxGrossAccountDebitUsdc;
        uint256 maxActionChargeUsdc;
        uint256 maxExplicitFeesUsdc;
        uint256 maxPostPositionSize;
        uint256 minPostSettlementBalanceUsdc;
        uint256 minPostPositionEquityUsdc;
        uint32 maxPostLeverageBps;
    }

    /// @notice Canonical, idempotent V2 order submission.
    struct OrderRequest {
        bytes32 clientOrderId;
        CfdTypes.Side side;
        uint256 sizeDelta;
        uint256 marginDelta;
        uint256 targetPrice;
        bool isClose;
        CloseMode closeMode;
        ExecutionBounds bounds;
    }

    /// @notice Permanent client-id resolution record.
    struct ClientIntent {
        uint64 orderId;
        bytes32 intentHash;
    }

    /// @notice Identity and policy retained only while an order is pending.
    struct PendingIntent {
        address account;
        bytes32 clientOrderId;
        bytes32 intentHash;
        uint256 executionBountyUsdc;
        CloseMode closeMode;
        uint64 positionEpoch;
        CfdTypes.Side positionSide;
        uint256 positionSize;
        CfdEnginePlanTypes.CloseCommitment commitment;
        ExecutionBounds bounds;
    }

    /// @notice Normalized economic assessment produced before Engine state is applied.
    struct ExecutionAssessment {
        ExecutionMode mode;
        uint256 executionNotionalUsdc;
        uint256 grossAccountDebitUsdc;
        uint256 actionChargeAssessedUsdc;
        uint256 actionChargeCollectedUsdc;
        uint256 explicitFeesUsdc;
        uint256 preSettlementBalanceUsdc;
        uint256 postSettlementBalanceUsdc;
        int256 realizedPnlUsdc;
        int256 vpiUsdc;
        uint256 carryUsdc;
        uint256 executionFeeUsdc;
        uint256 frozenSpreadUsdc;
        uint256 preTraderClaimUsdc;
        uint256 postTraderClaimUsdc;
        uint256 postPositionSize;
        uint256 postPositionMarginUsdc;
        int256 postPositionEquityUsdc;
        uint256 postLeverageBps;
        CloseEconomics close;
    }

    /// @notice Typed failure evidence included in a terminal receipt.
    struct FailureDetails {
        bytes4 selector;
        uint8 category;
        uint8 code;
        ConstraintKind constraint;
        uint256 actual;
        uint256 limit;
        bytes32 revertDataHash;
    }

    /// @notice Complete normalized economics emitted for a terminal order.
    struct OrderEconomics {
        uint256 executionNotionalUsdc;
        int256 realizedPnlUsdc;
        int256 vpiUsdc;
        int256 carryUsdc;
        uint256 executionFeeUsdc;
        uint256 frozenSpreadUsdc;
        uint256 actionChargeAssessedUsdc;
        uint256 actionChargeCollectedUsdc;
        uint256 grossAccountDebitUsdc;
        uint256 preSettlementBalanceUsdc;
        uint256 postSettlementBalanceUsdc;
        uint256 preTraderClaimBalanceUsdc;
        uint256 postTraderClaimBalanceUsdc;
        uint256 postPositionSize;
        uint256 postPositionMarginUsdc;
        int256 postPositionEquityUsdc;
        uint256 postLeverageBps;
        CloseEconomics close;
    }

    /// @notice Full fixed-shape input authenticated and emitted by the lifecycle book.
    struct OrderReceipt {
        uint64 orderId;
        address account;
        bytes32 clientOrderId;
        bytes32 intentHash;
        bytes32 expectedConfigHash;
        bytes32 observedConfigHash;
        LifecycleStatus status;
        TerminalReason reason;
        ExecutionMode executionMode;
        address executor;
        PriceSource priceSource;
        uint256 executionPrice;
        uint256 neutralMarkPrice;
        uint256 poolDepthUsdc;
        uint64 oraclePublishTime;
        bool priceReachedEngine;
        uint256 bountyUsdc;
        address bountyRecipient;
        BountyDisposition bountyDisposition;
        FailureDetails failure;
        OrderEconomics economics;
        CloseMode closeMode;
        CfdEnginePlanTypes.CloseCommitment commitment;
        BountyAccounting bounty;
    }

    /// @notice Two-slot durable terminal summary. Full history is carried by the authenticated receipt event.
    struct TerminalOutcome {
        address account;
        uint64 terminalBlock;
        LifecycleStatus status;
        TerminalReason reason;
        bytes32 receiptHash;
    }

    /// @notice Historical full outcome projection; consumers reconstruct this from a verified receipt event.
    struct CompactOutcome {
        address account;
        bytes32 clientOrderId;
        bytes32 intentHash;
        bytes32 expectedConfigHash;
        bytes32 observedConfigHash;
        LifecycleStatus status;
        TerminalReason reason;
        ExecutionMode executionMode;
        PriceSource priceSource;
        BountyDisposition bountyDisposition;
        uint64 terminalBlock;
        uint64 terminalTime;
        uint64 oraclePublishTime;
        address executor;
        address bountyRecipient;
        uint256 executionPrice;
        uint256 bountyUsdc;
        bytes4 failureSelector;
        uint8 failureCategory;
        uint8 failureCode;
        ConstraintKind failedConstraint;
        bytes32 revertDataHash;
        bytes32 receiptHash;
    }

    /// @notice Machine-readable result of one Router execution request.
    struct ExecutionResult {
        uint64 orderId;
        LifecycleStatus status;
        TerminalReason terminalReason;
        PendingReason pendingReason;
        bytes32 receiptHash;
    }

    /// @notice Machine-readable result of one bounded batch request.
    struct BatchResult {
        uint64 nextOrderId;
        uint32 terminalCount;
        PendingReason stopReason;
    }

    /// @notice Places a tagged digest in the reserved protocol-generated client-id namespace.
    function protocolClientOrderId(
        bytes32 digest
    ) internal pure returns (bytes32 clientOrderId) {
        return bytes32(PROTOCOL_CLIENT_ORDER_ID_PREFIX) | bytes32(uint256(digest) & type(uint192).max);
    }

    /// @notice Returns whether a client id belongs to the reserved protocol-generated namespace.
    function isProtocolClientOrderId(
        bytes32 clientOrderId
    ) internal pure returns (bool) {
        return bytes8(clientOrderId) == PROTOCOL_CLIENT_ORDER_ID_PREFIX;
    }

}
