// Generated by scripts/generate-close-v3-abi.py; retain historical ABI exports separately.

export const orderRouterV3Abi = [
  {
    "type": "function",
    "name": "commitOrder",
    "inputs": [
      {
        "name": "request",
        "type": "tuple",
        "internalType": "struct OrderV2Types.OrderRequest",
        "components": [
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "side",
            "type": "uint8",
            "internalType": "enum CfdTypes.Side"
          },
          {
            "name": "sizeDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "targetPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "isClose",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "closeMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.CloseMode"
          },
          {
            "name": "bounds",
            "type": "tuple",
            "internalType": "struct OrderV2Types.ExecutionBounds",
            "components": [
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "allowedExecutionModes",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "expectedConfigHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "maxExecutionBountyUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExecutionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGrossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxActionChargeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExplicitFeesUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostPositionEquityUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostLeverageBps",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeOrder",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "pythUpdateData",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct OrderV2Types.ExecutionResult",
        "components": [
          {
            "name": "orderId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum OrderV2Types.LifecycleStatus"
          },
          {
            "name": "terminalReason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.TerminalReason"
          },
          {
            "name": "pendingReason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.PendingReason"
          },
          {
            "name": "receiptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "expireOrder",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct OrderV2Types.ExecutionResult",
        "components": [
          {
            "name": "orderId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum OrderV2Types.LifecycleStatus"
          },
          {
            "name": "terminalReason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.TerminalReason"
          },
          {
            "name": "pendingReason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.PendingReason"
          },
          {
            "name": "receiptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pendingTerminalExitId",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "CfdEngine__NoPositionToLiquidate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__AccountQueueCorrupt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__BatchBeforeQueueHead",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__BatchOrderNotCommitted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__CloseOnlyWindow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__CloseWithPositiveMargin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__CommitValidation",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__ConditionalTriggerFrozen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__DegradedMode",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__EmptyFeeds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__EmptyPythUpdateData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ExecutionBountyAboveGrossDebit",
    "inputs": [
      {
        "name": "executionBountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maximumGrossDebitUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__ExecutionConfigMismatch",
    "inputs": [
      {
        "name": "expectedConfigHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "currentConfigHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__GlobalQueueCorrupt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InsufficientFreeEquity",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InsufficientGas",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InsufficientPythFee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidBasePrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidCloseMode",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidEngineLens",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidExecutionModeMask",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidExecutionSidecar",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidKeeperSidecar",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidLifecycleBook",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidLiquidationBatchSize",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidOraclePrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidPletherOracle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidPolicyEvaluator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidProtectionPrices",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidSizeQuantum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidValidUntil",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__InvalidWeights",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__LengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__LiquidationOraclePriceTooStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__MarginQueueCorrupt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__MarkPriceOutOfOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__MevDetected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__MockOracleUnavailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__NoOpenPosition",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__NoOrdersToExecute",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__NoQueuedPosition",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__NotInSeedLifecycle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OracleConfidenceTooWide",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OraclePriceTooStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OraclePublishTimesDiverged",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OrderNotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OrderNotPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OrderNotQueueHead",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__OrderNotRiskOff",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__PendingOrdersExist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__PositionChanged",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__PredictableOpenInvalid",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionActive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionAlreadyActive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionMarkTooStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionNotArmed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionNotLatched",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ProtectionTriggerAlreadyMet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__SameBlockTrigger",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__SideMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__SizeExceedsQueued",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__TerminalExitActive",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__TerminalExitBusy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__TooManyPendingOrders",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__TriggerNotMet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__VaultRiskBlocked",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ZeroClientOrderId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ZeroPostLeverageBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ZeroSize",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__ZeroTargetPrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  }
] as const;

export const closePreviewV3Abi = [
  {
    "type": "function",
    "name": "fullExitBlockers",
    "inputs": [
      {
        "name": "engineAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "blockers",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "previewClose",
    "inputs": [
      {
        "name": "engineAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "request",
        "type": "tuple",
        "internalType": "struct OrderV2Types.OrderRequest",
        "components": [
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "side",
            "type": "uint8",
            "internalType": "enum CfdTypes.Side"
          },
          {
            "name": "sizeDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "targetPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "isClose",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "closeMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.CloseMode"
          },
          {
            "name": "bounds",
            "type": "tuple",
            "internalType": "struct OrderV2Types.ExecutionBounds",
            "components": [
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "allowedExecutionModes",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "expectedConfigHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "maxExecutionBountyUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExecutionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGrossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxActionChargeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExplicitFeesUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostPositionEquityUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostLeverageBps",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          }
        ]
      },
      {
        "name": "executor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "executionPrice",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "preview",
        "type": "tuple",
        "internalType": "struct CfdClosePreview.ClosePreview",
        "components": [
          {
            "name": "commitment",
            "type": "tuple",
            "internalType": "struct CfdEnginePlanTypes.CloseCommitment",
            "components": [
              {
                "name": "carryCollectedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryOutstandingUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromFreeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromPledgeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementBeforeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "freeSettlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "commitmentCarryUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "executionBountyUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assessment",
            "type": "tuple",
            "internalType": "struct OrderV2Types.ExecutionAssessment",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "enum OrderV2Types.ExecutionMode"
              },
              {
                "name": "executionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "grossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeAssessedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeCollectedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "explicitFeesUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "preSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "realizedPnlUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "vpiUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "carryUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "executionFeeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "frozenSpreadUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "preTraderClaimUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postTraderClaimUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionMarginUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionEquityUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "postLeverageBps",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "close",
                "type": "tuple",
                "internalType": "struct OrderV2Types.CloseEconomics",
                "components": [
                  {
                    "name": "postFreeSettlementUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "safeMarginReleaseUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeFromReleasedMarginUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "netReleasedMarginUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "priceLossUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "pricePnlClaimConsumedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "pricePnlPledgeConsumedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "priceLossWrittenOffUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeWithheldUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeWaivedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "CfdClosePreview__NotCloseOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdClosePreview__SponsoredAccountBusy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdClosePreview__SponsoredDeploymentMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdClosePreview__SponsoredIntentInvalid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdClosePreview__SubsidyMismatch",
    "inputs": [
      {
        "name": "expectedUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requiredUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdClosePreview__UncoveredCarry",
    "inputs": [
      {
        "name": "unpaidCarryUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdEngine__CloseSizeExceedsPosition",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdEngine__InsufficientCloseOrderBountyBacking",
    "inputs": [
      {
        "name": "requiredBountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "availableBackingUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "unpaidCarryUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdEngine__InvalidCloseSizeQuantum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdEngine__MarkPriceStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdEngine__NoOpenPosition",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdEngine__PartialCloseCarryUnfunded",
    "inputs": [
      {
        "name": "unpaidCarryUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdEngine__PartialCloseUnhealthy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdEngine__TypedOrderFailure",
    "inputs": [
      {
        "name": "failureCategory",
        "type": "uint8",
        "internalType": "enum CfdEnginePlanTypes.ExecutionFailurePolicyCategory"
      },
      {
        "name": "failureCode",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "isClose",
        "type": "bool",
        "internalType": "bool"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdEngine__ZeroAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdMath__InvalidSizeQuantum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__ConstraintViolation",
    "inputs": [
      {
        "name": "constraint",
        "type": "uint8",
        "internalType": "enum OrderV2Types.ConstraintKind"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__ExecutionModeDisallowed",
    "inputs": [
      {
        "name": "mode",
        "type": "uint8",
        "internalType": "enum OrderV2Types.ExecutionMode"
      },
      {
        "name": "allowedExecutionModes",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__InsufficientBountyBacking",
    "inputs": [
      {
        "name": "settlementUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "bountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__InvalidPlannerResult",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderRouter__CommitValidation",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderRouter__SideMismatch",
    "inputs": []
  }
] as const;

export const committedOrderV3Abi = [
  {
    "type": "function",
    "name": "assessCommittedOrder",
    "inputs": [
      {
        "name": "engineAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "executor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "executionPrice",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "assessment",
        "type": "tuple",
        "internalType": "struct OrderV2Types.ExecutionAssessment",
        "components": [
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.ExecutionMode"
          },
          {
            "name": "executionNotionalUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "grossAccountDebitUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "actionChargeAssessedUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "actionChargeCollectedUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "explicitFeesUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "preSettlementBalanceUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postSettlementBalanceUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "realizedPnlUsdc",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "vpiUsdc",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "carryUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "executionFeeUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "frozenSpreadUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "preTraderClaimUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postTraderClaimUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postPositionSize",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postPositionMarginUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postPositionEquityUsdc",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "postLeverageBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "close",
            "type": "tuple",
            "internalType": "struct OrderV2Types.CloseEconomics",
            "components": [
              {
                "name": "postFreeSettlementUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "safeMarginReleaseUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeFromReleasedMarginUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "netReleasedMarginUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "priceLossUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "pricePnlClaimConsumedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "pricePnlPledgeConsumedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "priceLossWrittenOffUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeWithheldUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeWaivedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "CfdEngine__TypedOrderFailure",
    "inputs": [
      {
        "name": "failureCategory",
        "type": "uint8",
        "internalType": "enum CfdEnginePlanTypes.ExecutionFailurePolicyCategory"
      },
      {
        "name": "failureCode",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "isClose",
        "type": "bool",
        "internalType": "bool"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdMath__InvalidSizeQuantum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__CommittedPolicyChanged",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__ConstraintViolation",
    "inputs": [
      {
        "name": "constraint",
        "type": "uint8",
        "internalType": "enum OrderV2Types.ConstraintKind"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__ExecutionModeDisallowed",
    "inputs": [
      {
        "name": "mode",
        "type": "uint8",
        "internalType": "enum OrderV2Types.ExecutionMode"
      },
      {
        "name": "allowedExecutionModes",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__InsufficientBountyBacking",
    "inputs": [
      {
        "name": "settlementUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "bountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__InvalidPlannerResult",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__ReservationMismatch",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "CfdOrderPolicyEvaluator__TerminalPositionChanged",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  }
] as const;

export const orderLifecycleV4Abi = [
  {
    "type": "function",
    "name": "CONFIG_SCHEMA_HASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "INTENT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "RECEIPT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentExecutionConfigHash",
    "inputs": [],
    "outputs": [
      {
        "name": "configHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "outcome",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "terminalOutcome",
        "type": "tuple",
        "internalType": "struct OrderV2Types.CompactOutcome",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "intentHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedConfigHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "observedConfigHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum OrderV2Types.LifecycleStatus"
          },
          {
            "name": "reason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.TerminalReason"
          },
          {
            "name": "executionMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.ExecutionMode"
          },
          {
            "name": "priceSource",
            "type": "uint8",
            "internalType": "enum OrderV2Types.PriceSource"
          },
          {
            "name": "bountyDisposition",
            "type": "uint8",
            "internalType": "enum OrderV2Types.BountyDisposition"
          },
          {
            "name": "terminalBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "terminalTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "oraclePublishTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "executor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bountyRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "executionPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bountyUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "failureSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "failureCategory",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "failureCode",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "failedConstraint",
            "type": "uint8",
            "internalType": "enum OrderV2Types.ConstraintKind"
          },
          {
            "name": "revertDataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "receiptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingIntent",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct OrderV2Types.PendingIntent",
        "components": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "intentHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "executionBountyUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "closeMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.CloseMode"
          },
          {
            "name": "positionEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "positionSide",
            "type": "uint8",
            "internalType": "enum CfdTypes.Side"
          },
          {
            "name": "positionSize",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "commitment",
            "type": "tuple",
            "internalType": "struct CfdEnginePlanTypes.CloseCommitment",
            "components": [
              {
                "name": "carryCollectedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryOutstandingUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromFreeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromPledgeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementBeforeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "freeSettlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "bounds",
            "type": "tuple",
            "internalType": "struct OrderV2Types.ExecutionBounds",
            "components": [
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "allowedExecutionModes",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "expectedConfigHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "maxExecutionBountyUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExecutionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGrossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxActionChargeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExplicitFeesUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostPositionEquityUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostLeverageBps",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "IntentRegistered",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "clientOrderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "intentHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "executionBountyUsdc",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "request",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct OrderV2Types.OrderRequest",
        "components": [
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "side",
            "type": "uint8",
            "internalType": "enum CfdTypes.Side"
          },
          {
            "name": "sizeDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginDelta",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "targetPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "isClose",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "closeMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.CloseMode"
          },
          {
            "name": "bounds",
            "type": "tuple",
            "internalType": "struct OrderV2Types.ExecutionBounds",
            "components": [
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "allowedExecutionModes",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "expectedConfigHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "maxExecutionBountyUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExecutionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGrossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxActionChargeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxExplicitFeesUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minPostPositionEquityUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxPostLeverageBps",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderFinalized",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "clientOrderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "receiptHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "terminalBlock",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "terminalTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "receipt",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct OrderV2Types.OrderReceipt",
        "components": [
          {
            "name": "orderId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "clientOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "intentHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedConfigHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "observedConfigHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum OrderV2Types.LifecycleStatus"
          },
          {
            "name": "reason",
            "type": "uint8",
            "internalType": "enum OrderV2Types.TerminalReason"
          },
          {
            "name": "executionMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.ExecutionMode"
          },
          {
            "name": "executor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "priceSource",
            "type": "uint8",
            "internalType": "enum OrderV2Types.PriceSource"
          },
          {
            "name": "executionPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "neutralMarkPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "poolDepthUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oraclePublishTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "priceReachedEngine",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "bountyUsdc",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bountyRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bountyDisposition",
            "type": "uint8",
            "internalType": "enum OrderV2Types.BountyDisposition"
          },
          {
            "name": "failure",
            "type": "tuple",
            "internalType": "struct OrderV2Types.FailureDetails",
            "components": [
              {
                "name": "selector",
                "type": "bytes4",
                "internalType": "bytes4"
              },
              {
                "name": "category",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "code",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "constraint",
                "type": "uint8",
                "internalType": "enum OrderV2Types.ConstraintKind"
              },
              {
                "name": "actual",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "limit",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "revertDataHash",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "economics",
            "type": "tuple",
            "internalType": "struct OrderV2Types.OrderEconomics",
            "components": [
              {
                "name": "executionNotionalUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "realizedPnlUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "vpiUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "carryUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "executionFeeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "frozenSpreadUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeAssessedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "actionChargeCollectedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "grossAccountDebitUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "preSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postSettlementBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "preTraderClaimBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postTraderClaimBalanceUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionSize",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionMarginUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "postPositionEquityUsdc",
                "type": "int256",
                "internalType": "int256"
              },
              {
                "name": "postLeverageBps",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "close",
                "type": "tuple",
                "internalType": "struct OrderV2Types.CloseEconomics",
                "components": [
                  {
                    "name": "postFreeSettlementUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "safeMarginReleaseUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeFromReleasedMarginUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "netReleasedMarginUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "priceLossUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "pricePnlClaimConsumedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "pricePnlPledgeConsumedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "priceLossWrittenOffUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeWithheldUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "actionChargeWaivedUsdc",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              }
            ]
          },
          {
            "name": "closeMode",
            "type": "uint8",
            "internalType": "enum OrderV2Types.CloseMode"
          },
          {
            "name": "commitment",
            "type": "tuple",
            "internalType": "struct CfdEnginePlanTypes.CloseCommitment",
            "components": [
              {
                "name": "carryCollectedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryOutstandingUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromFreeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyFromPledgeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementBeforeUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "settlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "freeSettlementAfterUsdc",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "bounty",
            "type": "tuple",
            "internalType": "struct OrderV2Types.BountyAccounting",
            "components": [
              {
                "name": "bountyEntitlementUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyPaidUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyRefundedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyRetainedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bountyForfeitedUsdc",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "discrepancy",
                "type": "uint8",
                "internalType": "enum OrderV2Types.ReservationDiscrepancy"
              }
            ]
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ClientIdConflict",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "clientOrderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "existingIntentHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "suppliedIntentHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ClientIdDomainMismatch",
    "inputs": [
      {
        "name": "clientOrderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "protocolIntent",
        "type": "bool",
        "internalType": "bool"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__CommitmentBoundExceeded",
    "inputs": [
      {
        "name": "constraint",
        "type": "uint8",
        "internalType": "enum OrderV2Types.ConstraintKind"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ExecutionBountyAboveBound",
    "inputs": [
      {
        "name": "actualBountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maximumBountyUsdc",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__InvalidProtectionAttempt",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__InvalidTerminalOutcome",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__OrderIdAlreadyUsed",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__OrderNotPending",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ProtectionAttemptAlreadyRegistered",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ReceiptIdentityMismatch",
    "inputs": [
      {
        "name": "orderId",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__TerminalClockOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ZeroAccount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ZeroClientOrderId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ZeroDependency",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderLifecycleBook__ZeroOrderId",
    "inputs": []
  }
] as const;
