#!/usr/bin/env python3
"""Regenerate new-stack SDK ABIs from `forge build --root packages/perps`. Historical exports are untouched."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--artifacts-dir", type=Path, default=root / "packages/perps/out")
args = parser.parse_args()
output = root / "packages/perps-aa-client/src/orderV3Abi.ts"
specs = {
    "orderRouterV3Abi": ("OrderRouter", {"commitOrder", "executeOrder", "expireOrder", "pendingTerminalExitId"}),
    "closePreviewV3Abi": ("CfdClosePreview", {"previewClose", "fullExitBlockers"}),
    "committedOrderV3Abi": ("CfdOrderPolicyEvaluator", {"assessCommittedOrder"}),
    "orderLifecycleV4Abi": ("OrderLifecycleBook", {"IntentRegistered", "OrderFinalized", "pendingIntent", "outcome", "currentExecutionConfigHash", "INTENT_TYPEHASH", "RECEIPT_TYPEHASH", "CONFIG_SCHEMA_HASH"}),
}
lines = ["// Generated by scripts/generate-close-v3-abi.py; retain historical ABI exports separately.\n"]
for export, (contract, names) in specs.items():
    artifact = json.loads((args.artifacts_dir / (contract + ".sol") / (contract + ".json")).read_text())
    abi = [item for item in artifact["abi"] if item.get("type") == "error" or item.get("name") in names]
    if contract == "CfdClosePreview":
        abi = [item for item in abi if item.get("name") != "previewClose" or item["inputs"][1]["type"] == "address"]
    lines.append(f"export const {export} = {json.dumps(abi, indent=2)} as const;\n")
output.write_text("\n".join(lines))
print(output.relative_to(root))
